INSERT INTO SUPER_HEROE (NOMBRE) VALUES ('Superman');    
INSERT INTO SUPER_HEROE (NOMBRE) VALUES ('Batman');    
INSERT INTO SUPER_HEROE (NOMBRE) VALUES ('Spiderman');
INSERT INTO SUPER_HEROE (NOMBRE) VALUES ('Deadpool');        